<script lang="ts">
    import { toastStore, type ToastSettings } from "@skeletonlabs/skeleton";


    let message = {error: false, message: ""}
    let disabled = false

    let _2fa: number;

    export let username: string
    export let password:string

    $:if (!_2fa){
        disabled = true
        message.message = "2FA code not inputted"
        message.error = true
    }else{
        disabled = false
        message.message = ""
        message.error = false
    }

    const t: ToastSettings = {
		message: 'resp',
		// Optional: Presets for primary | secondary | tertiary | warning
		preset: 'error',
		// Optional: The auto-hide settings
		autohide: true,
		timeout: 2000
	};

    async function retrylogin(){
        if (username && password){
			const loginresp = await fetch('/login', {
					method: 'POST',
					headers: {
						'Content-Type': 'application/json'
					},
					credentials: 'include',
					body: JSON.stringify({
						username,
						password,
						_2fa
					})
				})
				const login = await loginresp.json()
				if (!login.error){
					t.preset = 'success'
					t.message = 'Logged in!'
					toastStore.trigger(t)
					document.location = '/home'
				}else{
					t.message = login.error
					toastStore.trigger(t)
				}

		}
    }

</script>

<div class="space-y-2 flex flex-row flex-wrap justify-center">
    
    <h5 class="m-auto text-center w-full">Confirm 2FA</h5>

    
    <svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="w-32"><path d="M21 2l-2 2m-7.61 7.61a5.5 5.5 0 1 1-7.778 7.778 5.5 5.5 0 0 1 7.777-7.777zm0 0L15.5 7.5m0 0l3 3L22 7l-3-3m-3.5 3.5L19 4"></path></svg>

    <h5 class="m-auto text-center w-full">Enter the code generated by your authenticator app.</h5>

    <div class="space-y-4 w-full">
        <input type="number" bind:value={_2fa} placeholder="Input 2FA" class="input input-bordered input-primary w-full rounded-md" required>
        <h5 class="!text-xs mt-6 {message.error === true ? 'text-error-600' : 'text-success-600'}">{message.message??""}</h5>
    </div>

    

    <button on:click={retrylogin} class="btn variant-filled-primary btn-base rounded-md" disabled={disabled}>
        Confirm
    </button>

</div>
